apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  namespace: online-boutique
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - shop.mgaru.dev
      secretName: shop-server-tls
  rules:
    - host: shop.mgaru.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  namespace: online-boutique
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - chat.mgaru.dev
      secretName: chat-server-tls
  rules:
    - host: chat.mgaru.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-ui
                port:
                  number: 8501