apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yaml
- ingress.yml
images:
- name: mirondaniel7/adservice
  newName: mirondaniel7/adservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/cartservice
  newName: mirondaniel7/cartservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/chat-ollama
  newName: mirondaniel7/chat-ollama
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/checkoutservice
  newName: mirondaniel7/checkoutservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/currencyservice
  newName: mirondaniel7/currencyservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/emailservice
  newName: mirondaniel7/emailservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/frontend
  newName: mirondaniel7/frontend
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/loadgenerator
  newName: mirondaniel7/loadgenerator
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/ollama-connect
  newName: mirondaniel7/ollama-connect
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/ollama-custom
  newName: mirondaniel7/ollama-custom
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/paymentservice
  newName: mirondaniel7/paymentservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/productcatalogservice
  newName: mirondaniel7/productcatalogservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/recommendationservice
  newName: mirondaniel7/recommendationservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/shippingservice
  newName: mirondaniel7/shippingservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
- name: mirondaniel7/shoppingassistantservice
  newName: mirondaniel7/shoppingassistantservice
  newTag: 4a3ccf96b44fb6e9e3eabfd0e306874f0521e15d-25755962565
