name: Build and Push Microservices

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: k8s
    strategy:
      fail-fast: false
      matrix:
        service:
          - adservice
          - cartservice
          - chat-ollama
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - loadgenerator
          - ollama-connect
          - ollama-custom
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - shoppingassistantservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Lowercase Docker Username
        id: format_username
        run: echo "username=$(echo '${{ vars.DOCKER_USERNAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set Paths
        id: paths
        run: |
          if [[ "${{ matrix.service }}" == "cartservice" ]]; then
            echo "context=./src/${{ matrix.service }}/src" >> $GITHUB_OUTPUT
            echo "file=./src/${{ matrix.service }}/src/Dockerfile" >> $GITHUB_OUTPUT
          else
            echo "context=./src/${{ matrix.service }}" >> $GITHUB_OUTPUT
            echo "file=./src/${{ matrix.service }}/Dockerfile" >> $GITHUB_OUTPUT
          fi

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.paths.outputs.context }}
          file: ${{ steps.paths.outputs.file }}
          push: true
          tags: |
            ${{ steps.format_username.outputs.username }}/${{ matrix.service }}:latest
            ${{ steps.format_username.outputs.username }}/${{ matrix.service }}:${{ github.sha }}-${{ github.run_id }}
          cache-from: type=registry,ref=${{ steps.format_username.outputs.username }}/${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=${{ steps.format_username.outputs.username }}/${{ matrix.service }}:buildcache,mode=max

  update-argocd-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required to allow GitHub Actions to push commits back to the repo
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Image Tags with latest Commit SHA
        run: |
          cd prod
          # Array of all our services
          SERVICES=(adservice cartservice chat-ollama checkoutservice currencyservice emailservice frontend loadgenerator ollama-connect ollama-custom paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice)
          
          # Replace the images in the kustomization.yaml to point to the new build hash + run ID
          for SERVICE in "${SERVICES[@]}"; do
            kustomize edit set image mirondaniel7/$SERVICE=mirondaniel7/$SERVICE:${{ github.sha }}-${{ github.run_id }}
          done

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prod/kustomization.yaml
          git commit -m "Auto-update deployed images to version ${{ github.sha }}-${{ github.run_id }}" || echo "No changes to commit"
          git push
