name: Build and Push Microservices

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: k8s
    strategy:
      fail-fast: false
      matrix:
        service:
          - adservice
          - cartservice
          - chat-ollama
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - loadgenerator
          - ollama-connect
          - ollama-custom
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - shoppingassistantservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Lowercase Docker Username
        id: format_username
        run: echo "username=$(echo '${{ vars.DOCKER_USERNAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set Paths
        id: paths
        run: |
          if [[ "${{ matrix.service }}" == "cartservice" ]]; then
            echo "context=./src/${{ matrix.service }}/src" >> $GITHUB_OUTPUT
            echo "file=./src/${{ matrix.service }}/src/Dockerfile" >> $GITHUB_OUTPUT
          else
            echo "context=./src/${{ matrix.service }}" >> $GITHUB_OUTPUT
            echo "file=./src/${{ matrix.service }}/Dockerfile" >> $GITHUB_OUTPUT
          fi

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.paths.outputs.context }}
          file: ${{ steps.paths.outputs.file }}
          push: true
          tags: |
            ${{ steps.format_username.outputs.username }}/${{ matrix.service }}:latest
            ${{ steps.format_username.outputs.username }}/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.format_username.outputs.username }}/${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=${{ steps.format_username.outputs.username }}/${{ matrix.service }}:buildcache,mode=max
